### ISSUE TITLE
Revamp Timer

### ISSUE THREAD

**Issue by danielczheng** [aish12/MafiaManager#27]
Timer UI is messy and needs to be cleaned up. Should continue counting down even when not on the page. It would be nice if it counted down on the timer bar button too.

**Comment by robby-stigler** [comment]
Timer is now persistent and all start/pause/stop buttons work as intended, still need to clean the UI

**Comment by robby-stigler** [comment]
Timer now persistent, functional, with a clean UI. Colors for buttons can be changed in the constants in CoreGraphicsHelper if they do not look good
